version: "3.8"

services:
  # Laravel app
  app:
    image: php:8.3-fpm
    container_name: sfl_app
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - ./storage:/var/www/html/storage
    environment:
      APP_ENV: production
      APP_DEBUG: false
      APP_URL: https://sfl.starcraftfastest.us
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - mysql
      - redis
      - meilisearch

  # Nginx
  web:
    image: nginx:1.25
    container_name: sfl_nginx
    ports:
      - "81:80"
      - "443:443"
    volumes:
      - ./:/var/www/html
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    depends_on:
      - app

  # MySQL
  mysql:
    image: mysql:8.0
    container_name: sfl_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - sfl_mysql:/var/lib/mysql
    ports:
      - "3307:3306"

  # Redis
  redis:
    image: redis:7-alpine
    container_name: laravel_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  # Meilisearch
  meilisearch:
    image: getmeili/meilisearch:latest
    container_name: laravel_meilisearch
    environment:
      MEILI_MASTER_KEY: ${MEILISEARCH_MASTER_KEY}
    ports:
      - "7700:7700"
    volumes:
      - meili_data:/meili_data

volumes:
  sfl_mysql:
  redis_data:
  meili_data:

